### ISSUE TITLE
Have you considered using App Groups & Shared Data?

### ISSUE THREAD

**Issue by otzbergnet** [aidancornelius/EZProxy-Safari-App-Extension#1]
This is a very sweet app, I like what you've done here and I learned a lot from your code. Thank you for this!

I did however "worry" about the way you share data, it might be a completely unwarranted worry

Have you considered using Shared Data from App Groups, to reduce reliance on a hard coded path as in ViewController.swift on line 28

`let safariExtDir = home.appendingPathComponent("Library/Containers/net.stemtl.EZProxy.EZProxy-Safari/Data/Documents/")`

What you'd need to do:

1) Enable AppGroups for your Extension and the host app and give them an App Group like net.stemtl.shared

2) Wherever you get the data differently, you could then call upon the shared data 

`let fileManager = FileManager.default
guard let groupURL = fileManager.containerURL(forSecurityApplicationGroupIdentifier: "net.stemtl.shared") else {
    return ""
}
let safariExtDir = groupURL.appendingPathComponent("Library/Caches/")
let fileURL = safariExtDir.appendingPathComponent(file)`

Doing this will create a shared folder structure in:

/Users/USERNAME/Library/Group\ Containers/net.stemtl.shared

This structure will contain a Library folder, with Application Support, Caches and Preferences.

It is just a thought and I might totally get it wrong here. I just thought I'd share something I learned after playing with your app, since I felt it was valuable :)

**Comment by aidancornelius** [comment]
@otzbergnet Thank you for taking the time to look at this! I put this whole thing together very slapdash, so you're absolutely right there are much better/more secure ways to handle what I've done.  I'd gladly accept a fork then pull request if you wanted to do the above, I probably won't get to it for some months more otherwise. ☺️
