### ISSUE TITLE
Idea: Open Safari Preferences instead of GitHub Info Page

### ISSUE THREAD

**Issue by otzbergnet** [aidancornelius/EZProxy-Safari-App-Extension#3]
When a user clicks on "Safari" in your containing app, GitHub page is opened. Have you considered opening the Safari Preferences right away?

In ViewController ensure to import:

`import SafariServices.SFSafariApplication`

Then change your function to:

`@IBAction func safariButtonPressed(_ sender: Any) {
        SFSafariApplication.showPreferencesForExtension(withIdentifier: "com.cornelius-bell.EZProxy.EZProxy-Safari") { error in
            if let _ = error {
                // Insert code to inform the user that something went wrong.
            }
        }
    }`

When a user clicks this, s/he should be taken straight to the Safari Preferences of your app, helping them with most of the steps :)

**Comment by aidancornelius** [comment]
Thank you so much for this suggestion – I couldn't find where that feature existed. Apologies for the delay, I will be implementing this shortly.
