### ISSUE TITLE
Ezproxy button not working

### ISSUE THREAD

**Issue by jbgoette** [aidancornelius/EZProxy-Safari-App-Extension#5]
I have configured the proxy using the app and activated the extension, but when I press the button nothing happens. However, when I use the prepend the following before a page I would like to access http://ezproxy.lib.gla.ac.uk/login?url= I get taken to the appropriate login page.
<img width="500" alt="Screenshot 2020-04-23 09 55 46" src="https://user-images.githubusercontent.com/34738746/80074261-30706300-8549-11ea-827e-4681524d64c4.png">
<img width="775" alt="Screenshot 2020-04-23 09 56 03" src="https://user-images.githubusercontent.com/34738746/80074273-3403ea00-8549-11ea-8110-14514cac61cf.png">

**Comment by aidancornelius** [comment]
Hi @jbgoette thanks for raising this. I could replicate this in the old version but I think I have addressed this in the newer version. Sometimes it requires complete removal of the app and reinstallation to repair. I can access (to the login page at least) through your institutions ezproxy now.
