### ISSUE TITLE
The extension closes the window in Safari 15 

### ISSUE THREAD

**Issue by micheld93** [aidancornelius/EZProxy-Safari-App-Extension#8]
Hi, 

have a problem with the extension while using Safari 15 and version 2020.11 of the extension. When I click on the icon, the Safari windows is closing. I cannot download the paper or what else. Is it only me or is it a problem for all users?

Wishes

**Comment by aidancornelius** [comment]
Hi @micheld93,

Apologies for the delay. 

This may be a configuration-specific issue depending on how you have the URL configured in the app. 

Can I confirm your settings window looks something like this screenshot: 

https://www.icloud.com/iclouddrive/04543ZZzqxZqOUITv9dm6q2JA#Screen_Shot_2022-02-16_at_3.19.21_pm

And that the URL does not include 'http://' or 'https://' at the beginning, and no spaces at the end?

Best wishes,
Aidan

**Comment by micheld93** [comment]
Hi, 
sorry for my delay. The thesis needed to get done 😀
The problem was as simple as switching to "keep original" in the settings. I didn't see it before. 

Thanks and wishes, 
Michel
