### ISSUE TITLE
Closing windows with only one tab

### ISSUE THREAD

**Issue by jakub-oprsal** [aidancornelius/EZProxy-Safari-App-Extension#9]
Everything works great for me, with a small problem that I believe arises from the fact that the extension closes a tab before it opens a new one. This means that if there is only one tab open, it closes the window, and fails to open a new tab. This behaviour does not occur when I choose to 'Keep original' in the settings.

Safari
Version 15.3 (17612.4.9.1.8)

EZProxy Button
2022.02

**Comment by aidancornelius** [comment]
Thanks @jakub-oprsal! Should be fixed in c634994.
